eureka:
    client:
        service-url:
            defaultZone: http:www.wechatEureka.com/eureka

hystrix:
    command:
        circuitBreaker:
            requestVolumeThreshold: 10
            sleepWindowInMillseconds: 20000
feign:
  hystrix:
    enabled: true
